# Generated by Django 5.2.1 on 2025-05-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actor",
            options={"verbose_name": "Actor", "verbose_name_plural": "Actors"},
        ),
    ]
