# Generated by Django 5.2.1 on 2025-05-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0003_alter_actor_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actor",
            options={
                "ordering": ("first_name",),
                "verbose_name": "Actor",
                "verbose_name_plural": "Actors",
            },
        ),
    ]
